"""Provider-free contract tests generated by the reviewed frozen fixture asset.

The fake sys/_imp/pipe profile executes only the asset's observation encoder.
It is not a static-runtime startup or loader-enforcement acceptance claim.
"""

from __future__ import annotations

import builtins
import hashlib
import io
import json
from types import SimpleNamespace

import pytest

from lunar_evolution.python_fixture_observation import (
    PythonFixtureObservationError,
    adapt_static_python_observation,
)
from lunar_evolution.static_python_installation import (
    STATIC_PYTHON_BUILTIN_NAMES,
    STATIC_PYTHON_FROZEN_NAMES,
    STATIC_PYTHON_STARTUP_MODULES,
)
from tools.static_python_fixture.profile import BUILTINS, CONFIG, EXPECTED_STARTUP_MODULES, FROZEN
from tools.static_python_fixture.recipe import emit_assets

D = "a" * 64
BROKER_VALUE = {
    "protocol": "lunar-producer-broker-ipc-v1", "request_id": "req-1", "status": "completed",
    "http_status": 200, "body_base64": "aGVsbG8=",
}
BROKER = json.dumps(BROKER_VALUE, sort_keys=True, separators=(",", ":")).encode() + b"\n"


def _encoded(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def _refused(*_args, **_kwargs):
    raise ImportError("fixed inert loader refusal")


@pytest.fixture
def asset_observation(tmp_path):
    """Run emitted frozen_main against its explicit finite, simulated profile."""
    asset_dir = tmp_path / "assets"
    emit_assets(asset_dir)
    output = io.StringIO()
    stream = SimpleNamespace(write=output.write, flush=output.flush, encoding="utf-8", errors="strict")
    # These types mirror actual sys.flags members; safe_path/dev_mode are bools.
    flags = SimpleNamespace(
        isolated=CONFIG["isolated"], ignore_environment=1, no_site=1, no_user_site=1,
        utf8_mode=1, dont_write_bytecode=1, safe_path=True, dev_mode=False, optimize=0,
        hash_randomization=0,
    )
    modules = {
        name: SimpleNamespace(__spec__=SimpleNamespace(
            origin=None if name == "__main__" else "built-in" if name in BUILTINS else "frozen",
        )) for name in EXPECTED_STARTUP_MODULES
    }
    loader = SimpleNamespace(get_code=_refused, exec_module=_refused, create_module=_refused)
    modules["_frozen_importlib_external"].SourceFileLoader = lambda *_args: loader
    modules["_frozen_importlib_external"].SourcelessFileLoader = lambda *_args: loader
    modules["_frozen_importlib_external"].ExtensionFileLoader = lambda *_args: loader
    modules["_frozen_importlib_external"].PathFinder = SimpleNamespace(find_spec=_refused)
    modules["_frozen_importlib_external"].FileFinder = lambda *_args: SimpleNamespace(find_spec=_refused)
    modules["_frozen_importlib"].ModuleSpec = lambda *_args: object()
    fake_sys = SimpleNamespace(
        builtin_module_names=BUILTINS, modules=modules, path=[], path_hooks=[], flags=flags,
        version_info=(3, 13, 12, "final", 0), implementation=SimpleNamespace(cache_tag="cpython-313"),
        stdout=stream, stderr=SimpleNamespace(errors="strict"), _stdlib_dir=CONFIG["stdlib_dir"],
        argv=CONFIG["argv"], orig_argv=CONFIG["orig_argv"], executable=CONFIG["executable"],
        prefix=CONFIG["prefix"], base_prefix=CONFIG["base_prefix"], exec_prefix=CONFIG["exec_prefix"],
        base_exec_prefix=CONFIG["base_exec_prefix"], getfilesystemencoding=lambda: "utf-8",
        getfilesystemencodeerrors=lambda: "surrogateescape",
    )
    fake_imp = SimpleNamespace(_frozen_module_names=lambda: [entry[0] for entry in FROZEN],
                               extension_suffixes=list)
    request_frames = []

    def exchange(request):
        request_frames.append(request)
        return BROKER

    imports = {"sys": fake_sys, "_imp": fake_imp,
               "_lunar_fixture_pipe": SimpleNamespace(exchange=exchange)}

    def fixture_import(name, *_args, **_kwargs):
        if name not in imports:
            _refused()
        return imports[name]

    fixture_builtins = {**vars(builtins), "__import__": fixture_import}
    namespace = {"__builtins__": fixture_builtins}
    source = (asset_dir / "frozen_main.py").read_text()
    # Only the repository's reviewed emitted asset, with a closed fake import map.
    exec(compile(source, "<reviewed-frozen-fixture-contract>", "exec"), namespace)  # noqa: S102

    def observe(case="baseline"):
        output.seek(0)
        output.truncate()
        namespace["_main"](case)
        assert request_frames[-1] == (
            b'{"protocol":"lunar-producer-broker-ipc-v1","request_id":"req-1",'
            b'"body_base64":"aGVsbG8="}\n'
        )
        return output.getvalue().encode()

    return observe


def _adapt(value: object, **kwargs):
    return adapt_static_python_observation(
        value, binding_sha256=D, broker_transcript=BROKER, pycache_absent=True, **kwargs,
    )


def test_reviewed_profile_and_asset_output_project_to_feature191_dto(asset_observation):
    assert STATIC_PYTHON_BUILTIN_NAMES == tuple(sorted(BUILTINS))
    assert STATIC_PYTHON_FROZEN_NAMES == tuple(sorted(entry[0] for entry in FROZEN))
    assert STATIC_PYTHON_STARTUP_MODULES == tuple(sorted(EXPECTED_STARTUP_MODULES))
    raw = asset_observation()
    assert raw.endswith(b"\n") and not raw.endswith(b"\n\n")
    value = json.loads(raw)
    # Availability does not imply imports: real profile has unimported builtins.
    assert "gc" in value["builtin_names"] and "gc" not in value["origins"]
    assert value["prefix"] == "/lunar-static-fixture"
    item = _adapt(raw)
    assert item.version_major == 3 and item.version_minor == 13 and item.version_micro == 12
    assert item.execution_performed is True and item.sys_path == ()
    assert item.abi_profile == "cp313-release-gil"
    assert item.startup_modules == STATIC_PYTHON_STARTUP_MODULES
    assert item.computation_sha256 == hashlib.sha256(b"285").hexdigest()
    assert item.broker_transcript_sha256 == hashlib.sha256(BROKER).hexdigest()
    assert item.runtime_load_protection is False
    assert item.observation_sha256 == item.digest()
    assert _adapt(raw[:-1]) == item


def test_placeholder_binding_cannot_project_runtime_evidence(asset_observation):
    with pytest.raises(PythonFixtureObservationError, match="binding_invalid"):
        adapt_static_python_observation(
            asset_observation(), binding_sha256="0" * 64,
            broker_transcript=BROKER, pycache_absent=True,
        )


def test_loader_negative_asset_requires_all_fixed_routes_to_refuse(asset_observation):
    value = json.loads(asset_observation("loader-negative"))
    assert _adapt(value).startup_modules == STATIC_PYTHON_STARTUP_MODULES
    value["loader_negative"]["direct"][-1] = False
    with pytest.raises(PythonFixtureObservationError, match="loader_negative_failed"):
        _adapt(value)


@pytest.mark.parametrize("field,changed", [
    ("executable", "/usr/bin/python3"), ("prefix", "/lunar-static-python-fixture"),
    ("base_prefix", "/tmp/host"), ("sys_path", ["/tmp"]),
    ("runtime_load_protection", True), ("computed", 284), ("cache_tag", "cpython-312"),
    ("version_info", [3, 13, 11, "final", 0]), ("version_info", [3, 13, 12, "alpha", 0]),
    ("version_info", [3, 13, 12, "final", False]),
])
def test_host_substitution_version_and_claims_are_rejected(asset_observation, field, changed):
    value = json.loads(asset_observation())
    value[field] = changed
    with pytest.raises(PythonFixtureObservationError):
        _adapt(value)


@pytest.mark.parametrize("field", ["builtin_names", "frozen_names", "origins"])
def test_exact_available_and_startup_inventories_are_bound(asset_observation, field):
    value = json.loads(asset_observation())
    if field == "origins":
        value[field].pop("sys")
    else:
        value[field].pop()
    with pytest.raises(PythonFixtureObservationError, match="module_inventory_drift"):
        _adapt(value)


@pytest.mark.parametrize("changed", [1, "true", None])
def test_actual_boolean_sys_flags_have_exact_types(asset_observation, changed):
    value = json.loads(asset_observation())
    value["flags"]["safe_path"] = changed
    with pytest.raises(PythonFixtureObservationError, match="flags_invalid"):
        _adapt(value)


@pytest.mark.parametrize("transcript", [
    b'not-json "protocol":"lunar-producer-broker-ipc-v1" "request_id":"req-1" "status":"completed"\n',
    _encoded({**BROKER_VALUE, "status": "failed", "decoy": {"status": "completed"}}) + b"\n",
    _encoded({**BROKER_VALUE, "request_id": "wrong", "decoy": {"request_id": "req-1"}}) + b"\n",
    _encoded({**BROKER_VALUE, "http_status": True}) + b"\n",
    _encoded({**BROKER_VALUE, "body_base64": "!not-base64!"}) + b"\n",
    BROKER[:-2] + b',"status":"completed"}\n',
    BROKER + BROKER,
    BROKER + b"\n",
    BROKER[:-1],
])
def test_adversarial_broker_transcript_cannot_match_nested_or_multiple_frames(asset_observation, transcript):
    value = json.loads(asset_observation())
    value["broker_response_bytes"] = len(transcript)
    with pytest.raises(PythonFixtureObservationError, match="broker_transcript_mismatch"):
        adapt_static_python_observation(value, binding_sha256=D, broker_transcript=transcript, pycache_absent=True)


def test_missing_independent_pycache_evidence_is_rejected(asset_observation):
    with pytest.raises(PythonFixtureObservationError, match="pycache_missing"):
        adapt_static_python_observation(asset_observation(), binding_sha256=D,
                                        broker_transcript=BROKER, pycache_absent=False)


def test_duplicate_or_more_than_one_terminal_newline_is_rejected(asset_observation):
    raw = asset_observation()
    with pytest.raises(PythonFixtureObservationError, match="noncanonical_json"):
        _adapt(raw + b"\n")
    duplicate = raw[:-2] + b',"computed":285}\n'
    with pytest.raises(PythonFixtureObservationError, match="duplicate_json_key"):
        _adapt(duplicate)


class _HostileList(list):
    def __iter__(self):
        pytest.fail("nested list subclass callback must not run")


class _HostileDict(dict):
    def __iter__(self):
        pytest.fail("mapping subclass callback must not run")


class _HostileText(str):
    def __eq__(self, _other):
        pytest.fail("string subclass callback must not run")


@pytest.mark.parametrize("location", ["root", "flags", "origins", "builtin_names", "fixture_case"])
def test_direct_dict_refuses_nested_callback_classes_before_serialization(asset_observation, location):
    value = json.loads(asset_observation())
    if location == "root":
        value = _HostileDict(value)
    elif location in {"flags", "origins"}:
        value[location] = _HostileDict(value[location])
    elif location == "builtin_names":
        value[location] = _HostileList(value[location])
    else:
        value[location] = _HostileText(value[location])
    with pytest.raises(PythonFixtureObservationError):
        _adapt(value)


def test_direct_dict_aggregate_size_is_bounded_before_digest(asset_observation, monkeypatch):
    import lunar_evolution.python_fixture_observation as adapter

    value = json.loads(asset_observation())
    value["builtin_names"] = ["x" * 4096] * 65
    monkeypatch.setattr(adapter, "_canonical", lambda _value: pytest.fail("over-size shape must fail first"))
    with pytest.raises(PythonFixtureObservationError, match="record_too_large"):
        _adapt(value)


@pytest.mark.parametrize("computed", [285.0, True])
def test_computation_rejects_float_and_boolean_equality(asset_observation, computed):
    value = json.loads(asset_observation())
    value["computed"] = computed
    with pytest.raises(PythonFixtureObservationError, match="fixture_result_invalid"):
        _adapt(value)


@pytest.mark.parametrize("name,origin", [("sys", None), ("sys", "frozen"), ("abc", "built-in"), ("__main__", "frozen")])
def test_each_finite_startup_module_requires_its_correct_origin(asset_observation, name, origin):
    value = json.loads(asset_observation())
    value["origins"][name]["origin"] = origin
    with pytest.raises(PythonFixtureObservationError, match="origin_external"):
        _adapt(value)


def test_text_encoding_failures_are_fixed_errors():
    with pytest.raises(PythonFixtureObservationError, match="json_invalid"):
        _adapt("\ud800")
